### ISSUE TITLE
Symlinks not supported

### ISSUE THREAD

**Issue by mengesb** [xaque208/puppet-poudriere#21]
Report from Puppet shows that symlinks are not supported:

Warning: Symlinks in modules are unsupported. Please investigate symlink zleslie-poudriere-0.1.3/spec/fixtures/modules/poudriere/manifests->../../../../manifests.
Warning: Symlinks in modules are unsupported. Please investigate symlink zleslie-poudriere-0.1.3/spec/fixtures/modules/poudriere/templates->../../../../templates.

I'm sure duplication of files are not optimal, however it appears that per Puppet v3.7.1 this isn't supported.

**Comment by xaque208** [comment]
How did you install the module?

**Comment by mengesb** [comment]
Using 'puppet module install zleslie-poudriere --modulepath ${PWD}/modules'

~Brian

**Comment by xaque208** [comment]
If my CI does it job, 0.1.4 should be posted soon that should address this.

**Comment by xaque208** [comment]
Thanks for the issue.

**Comment by mengesb** [comment]
I'll look out for it on the forge and see if the issue persists

**Comment by xaque208** [comment]
Well  my CI is down with a failed NIC.  I posted manually.  Let me know how it goes.

**Comment by mengesb** [comment]
Confirmed that a fresh install and upgrade do not complain about symlinks.

~Brian
