### ISSUE TITLE
Still need cron_enable in init.pp manifest

### ISSUE THREAD

**Issue by b4ldr** [xaque208/puppet-poudriere#24]
In init.pp manifest you have a block[1] indicating that cron_enable and cron_interval have been deprecated.  however these values are both required for the default portstree[2].  can the old parameters be renamed to portstree_default_cron_enable and portstree_default_cron_interval?

[1]https://github.com/xaque208/puppet-poudriere/blob/master/manifests/init.pp#L71-L77
[2]https://github.com/xaque208/puppet-poudriere/blob/master/manifests/init.pp#L82-L87

**Comment by xaque208** [comment]
Yes, I've not actually updated my own manifests to reflect that deprecation.  As long as the readme stays accurate, I'm amenable.

**Comment by b4ldr** [comment]
was just going through issues and i think this can be closed.  looks like you no longer create the default portstree so i think this can be closed.  however turns out i did do the work but forgot to create a pull, sorry.  if you still want it happy to create a pull but i dont think its needed

**Comment by xaque208** [comment]
No worries.  Thanks for coming back @b4ldr.
